name: Ultimatextile
favicon: null
layout_spectrum: 0.64541523065418
typography_spectrum: 0.7421222778502852
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.44260065723210573
  lightness: 0.217906340258196
  saturation: 0.7777711434755474
  rhythmicContrast: 0.27100337436422706
purpose: []
